--
-- Type: TABLE; Owner: TM_CZ; Name: ANNOTATION_DEAPP
--
 CREATE TABLE "TM_CZ"."ANNOTATION_DEAPP" 
  (	"GPL_ID" VARCHAR2(50 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" VARCHAR2(100 BYTE), 
"PROBESET_ID" NUMBER(22,0), 
"ORGANISM" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

