--
-- Type: TABLE; Owner: TM_CZ; Name: CZ_DATA_PROFILE_COLUMN_EXCLUSI
--
  CREATE TABLE "TM_CZ"."CZ_DATA_PROFILE_COLUMN_EXCLUSI" 
   (	"TABLE_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"EXCLUSION_REASON" VARCHAR2(2000 BYTE), 
	"ETL_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  TABLESPACE "TRANSMART" ;
