--
-- Type: TABLE; Owner: TM_CZ; Name: CZ_RWG_INVALID_TERMS
--
 CREATE TABLE "TM_CZ"."CZ_RWG_INVALID_TERMS" 
  (	"STUDY_ID" VARCHAR2(500 BYTE), 
"CATEGORY_NAME" VARCHAR2(500 BYTE), 
"TERM_NAME" VARCHAR2(500 BYTE), 
"IMPORT_DATE" DATE DEFAULT SYSDATE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

