--
-- Type: TABLE; Owner: TM_CZ; Name: DE_SUBJECT_RBM_DATA_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_SUBJECT_RBM_DATA_RELEASE" 
  (	"TRIAL_NAME" VARCHAR2(100 BYTE), 
"ANTIGEN_NAME" VARCHAR2(100 BYTE), 
"N_VALUE" NUMBER, 
"PATIENT_ID" NUMBER(38,0), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" NUMBER(10,0), 
"ASSAY_ID" NUMBER, 
"NORMALIZED_VALUE" NUMBER(18,5), 
"CONCEPT_CD" VARCHAR2(100), 
"TIMEPOINT" VARCHAR2(250 BYTE), 
"DATA_UID" VARCHAR2(100 BYTE), 
"VALUE" NUMBER, 
"LOG_INTENSITY" NUMBER(38,4), 
"MEAN_INTENSITY" NUMBER(38,4), 
"STDDEV_INTENSITY" NUMBER(38,4), 
"MEDIAN_INTENSITY" NUMBER(38,4), 
"ZSCORE" NUMBER(38,4), 
"RBM_PANEL" VARCHAR2(50 BYTE), 
"RELEASE_STUDY" VARCHAR2(15 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

