--
-- Type: TABLE Owner: SEARCHAPP; Name: IMPORT_XNAT_CONFIGURATION
--
CREATE TABLE "SEARCHAPP"."IMPORT_XNAT_CONFIGURATION"
 (     "ID" NUMBER(10,0) NOT NULL,
"VERSION" NUMBER(10,0) NOT NULL,
"NAME" VARCHAR2(255) NOT NULL,
"DESCRIPTION" CLOB,
"URL" VARCHAR2(255) NOT NULL,
"USERNAME" VARCHAR2(255) NOT NULL,
"PROJECT" VARCHAR2(255) NOT NULL,
"NODE" VARCHAR2(255) NOT NULL,
 CONSTRAINT "IMPORT_XNAT_CONFIG_PK" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
 ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: TRIGGER; Owner: SEARCHAPP; Name: TRG_IMPORT_XNAT_CONFIG_ID
--
  CREATE OR REPLACE TRIGGER "SEARCHAPP"."TRG_IMPORT_XNAT_CONFIG_ID" 
BEFORE INSERT ON "SEARCHAPP"."IMPORT_XNAT_CONFIGURATION"
FOR EACH ROW
BEGIN
SELECT SEQ_SEARCH_DATA_ID.nextval
INTO :new.id
FROM dual;
END;
/
ALTER TRIGGER "SEARCHAPP"."TRG_IMPORT_XNAT_CONFIG_ID" ENABLE;
