--
-- Type: TABLE; Owner: SEARCHAPP; Name: XNAT_SUBJECT
--
CREATE TABLE "SEARCHAPP"."XNAT_SUBJECT"
 (   "TSMART_SUBJECTID" VARCHAR2(100),
"XNAT_SUBJECTID" VARCHAR2(100),
"XNAT_PROJECT" VARCHAR2(80),
"ID" number(10,0) NOT NULL,
 CONSTRAINT "XNAT_SUBJECT_PKEY" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "INDX" ENABLE
) SEGMENT CREATION IMMEDIATE
TABLESPACE "TRANSMART" ;

-- Type: TRIGGER; Owner: SEARCHAPP; Name: TRG_XNAT_SUBJECT_ID
--
CREATE OR REPLACE TRIGGER "SEARCHAPP"."TRG_XNAT_SUBJECT_ID" 
BEFORE INSERT ON "SEARCHAPP"."XNAT_SUBJECT"
FOR EACH ROW
BEGIN
SELECT SEQ_SEARCH_DATA_ID.nextval
INTO :new.id
FROM dual;
END;
/
ALTER TRIGGER "SEARCHAPP"."TRG_XNAT_SUBJECT_ID" ENABLE;
