--
-- Type: TABLE; Owner: I2B2IMDATA; Name: IM_MPI_DEMOGRAPHICS
--
 CREATE TABLE "I2B2IMDATA"."IM_MPI_DEMOGRAPHICS"
  (	"GLOBAL_ID" VARCHAR2(200 BYTE) NOT NULL ENABLE,
"GLOBAL_STATUS" VARCHAR2(50 BYTE),
"DEMOGRAPHICS" VARCHAR2(400 BYTE),
"UPDATE_DATE" DATE,
"DOWNLOAD_DATE" DATE,
"IMPORT_DATE" DATE,
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE),
"UPLOAD_ID" NUMBER(38,0),
 CONSTRAINT "IM_MPI_DEMOGRAPHICS_PK" PRIMARY KEY ("GLOBAL_ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
