--
-- Type: TABLE; Owner: I2B2IMDATA; Name: IM_PROJECT_PATIENTS
--
 CREATE TABLE "I2B2IMDATA"."IM_PROJECT_PATIENTS"
  (	"PROJECT_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"GLOBAL_ID" VARCHAR2(200 BYTE) NOT NULL ENABLE,
"PATIENT_PROJECT_STATUS" VARCHAR2(50 BYTE),
"UPDATE_DATE" DATE,
"DOWNLOAD_DATE" DATE,
"IMPORT_DATE" DATE,
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE),
"UPLOAD_ID" NUMBER(38,0),
 CONSTRAINT "IM_PROJECT_PATIENTS_PK" PRIMARY KEY ("PROJECT_ID", "GLOBAL_ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
