--
-- Type: TABLE; Owner: I2B2IMDATA; Name: IM_TEMP_SITE
--
 CREATE GLOBAL TEMPORARY TABLE "I2B2IMDATA"."IM_TEMP_SITE"
  (	"LCL_SITE" VARCHAR2(50 BYTE),
"LCL_ID" VARCHAR2(200 BYTE),
"PROJECT_ID" VARCHAR2(50 BYTE)
  ) ON COMMIT PRESERVE ROWS ;
