echo "------------------------------------------------------------------"
echo "|  Script for installing transmart app and data on Ubuntu 14.04  |"
echo "|  Note: this script uses the 'sudo' command which will time out |"
echo "|  after 15 minutes; because of this, when actions that a longer |"
echo "|  time the 15 minutes are run, then you will have to reenter    |"
echo "|  the sudo password. If you wish, you can change this behavior  |"
echo "|  before running the script. To do so, kill the script now      |"
echo "|  with ^C (control-c) and follow the instructions here:         |"
echo "|  https://help.ubuntu.com/community/RootSudoTimeout             |"
echo "|  Then, restart the script and enter the sudo root password     |"
echo "|  normally to continue running the script.                      |"
echo "------------------------------------------------------------------"
