--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_DATA_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_DATA_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_ASSAY_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_ASSAY_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: TT
--
CREATE SEQUENCE  "DEAPP"."TT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: METABOLITE_SUP_PTH_ID
--
CREATE SEQUENCE  "DEAPP"."METABOLITE_SUP_PTH_ID"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: METABOLITE_SUB_PTH_ID
--
CREATE SEQUENCE  "DEAPP"."METABOLITE_SUB_PTH_ID"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: METABOLOMICS_ANNOT_ID
--
CREATE SEQUENCE  "DEAPP"."METABOLOMICS_ANNOT_ID"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--
-- Type: SEQUENCE; Owner: DEAPP; Name: SEQ_MRNA_PARTITION_ID
--
CREATE SEQUENCE  "DEAPP"."SEQ_MRNA_PARTITION_ID"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--
-- Type: TYPE; Owner: DEAPP; Name: NUMBER_TABLE
--
  CREATE OR REPLACE TYPE "DEAPP"."NUMBER_TABLE" IS TABLE OF NUMBER
/
--
-- Type: TYPE; Owner: DEAPP; Name: VARCHAR_TABLE
--
  CREATE OR REPLACE TYPE "DEAPP"."VARCHAR_TABLE" IS TABLE OF VARCHAR2(1000)
/
