--
-- Type: TABLE; Owner: DEAPP; Name: DE_GENE_INFO
--
 CREATE TABLE "DEAPP"."DE_GENE_INFO"
  (	"GENE_INFO_ID" NUMBER(22,0) NOT NULL ENABLE,
"GENE_SOURCE_ID" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE,
"ENTREZ_ID" NUMBER(10,0),
"GENE_SYMBOL" VARCHAR2(100 BYTE) NOT NULL ENABLE,
"GENE_NAME" VARCHAR2(100 BYTE),
"CHROM" VARCHAR2(40 BYTE) NOT NULL ENABLE,
"CHROM_START" NUMBER,
"CHROM_STOP" NUMBER,
"STRAND" NUMBER(2,0),
 CONSTRAINT "DE_GENE_INFO_PK" PRIMARY KEY ("GENE_INFO_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE,
 CONSTRAINT "DE_GENE_INFO_UK" UNIQUE ("GENE_SOURCE_ID", "GENE_SYMBOL")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING
 TABLESPACE "TRANSMART" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: GENE_INFO_SOURCE_FK
--
ALTER TABLE "DEAPP"."DE_GENE_INFO" ADD CONSTRAINT "GENE_INFO_SOURCE_FK" FOREIGN KEY ("GENE_SOURCE_ID")
 REFERENCES "DEAPP"."DE_GENE_SOURCE" ("GENE_SOURCE_ID") ON DELETE CASCADE ENABLE;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_GI_EID_GS_ID_IDX
--
CREATE INDEX "DEAPP"."DE_GI_EID_GS_ID_IDX" ON "DEAPP"."DE_GENE_INFO" ("ENTREZ_ID", "GENE_SOURCE_ID")
TABLESPACE "INDX" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_GI_GS_IDX
--
CREATE INDEX "DEAPP"."DE_GI_GS_IDX" ON "DEAPP"."DE_GENE_INFO" ("GENE_SYMBOL")
TABLESPACE "INDX" ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_DE_GENE_INFO_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_DE_GENE_INFO_ID"
BEFORE
  INSERT ON DEAPP.DE_GENE_INFO FOR EACH ROW
BEGIN
  IF inserting THEN
    IF :NEW.GENE_INFO_ID IS NULL THEN
        SELECT DEAPP.SEQ_DATA_ID.nextval INTO :NEW.GENE_INFO_ID FROM dual;
    END IF;
  END IF;
END;
/
ALTER TRIGGER "DEAPP"."TRG_DE_GENE_INFO_ID" ENABLE;
