--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_MIRNA_DATA
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_MIRNA_DATA"
  (	"TRIAL_SOURCE" VARCHAR2(200 BYTE),
"TRIAL_NAME" VARCHAR2(100 BYTE),
"ASSAY_ID" NUMBER(18,0) NOT NULL ENABLE,
"PATIENT_ID" NUMBER(18,0),
"RAW_INTENSITY" NUMBER,
"LOG_INTENSITY" NUMBER,
"PROBESET_ID" NUMBER(22,0) NOT NULL ENABLE,
"ZSCORE" NUMBER(18,9),
 CONSTRAINT "DE_SUBJECT_MIRNA_DATA_PK" PRIMARY KEY ("ASSAY_ID", "PROBESET_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
