--
-- Type: TABLE; Owner: DEAPP; Name: DE_XTRIAL_METADATA
--
 CREATE TABLE "DEAPP"."DE_XTRIAL_METADATA"
  (	"MODIFIER_CD" VARCHAR2(50 BYTE),
"VALTYPE_CD" VARCHAR2(10 BYTE),
"STD_UNITS" VARCHAR2(50 BYTE),
"VISIT_IND" CHAR(1 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
