--
-- Type: TABLE; Owner: DEAPP; Name: DE_XTRIAL_NODE
--
 CREATE TABLE "DEAPP"."DE_XTRIAL_NODE"
  (	"MODIFIER_PATH" VARCHAR2(700 BYTE) NOT NULL ENABLE,
"MODIFIER_CD" VARCHAR2(50 BYTE),
"NAME_CHAR" VARCHAR2(2000 BYTE),
"MODIFIER_BLOB" CLOB,
"UPDATE_DATE" DATE,
"DOWNLOAD_DATE" DATE,
"IMPORT_DATE" DATE,
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE),
"UPLOAD_ID" NUMBER(18,0),
"MODIFIER_LEVEL" NUMBER(18,0),
"MODIFIER_NODE_TYPE" VARCHAR2(10),
 CONSTRAINT "DE_XTRIAL_NODE_PK" PRIMARY KEY ("MODIFIER_PATH")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART"
LOB ("MODIFIER_BLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--
-- Type: INDEX; Owner: DEAPP; Name: MD_IDX_UPLOADID
--
CREATE INDEX "DEAPP"."XN_IDX_UPLOADID" ON "DEAPP"."DE_XTRIAL_NODE" ("UPLOAD_ID")
TABLESPACE "INDX" ;
