--
-- Type: TABLE; Owner: DEAPP; Name: KEGG
--
 CREATE TABLE "DEAPP"."KEGG" 
  (	"PATHWAY" VARCHAR2(100 BYTE), 
"GENE_ID" VARCHAR2(100 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

