--
-- Type: TABLE; Owner: I2B2METADATA; Name: QUERY1
--
 CREATE TABLE "I2B2METADATA"."QUERY1"
  (	"TRIALNUMBER" VARCHAR2(255),
"DESCRIPTION" NCLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2"
LOB ("DESCRIPTION") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
