--
-- Type: TABLE; Owner: I2B2METADATA; Name: TM_TRIAL_NODES
--
 CREATE TABLE "I2B2METADATA"."TM_TRIAL_NODES"
  (	"C_FULLNAME" VARCHAR2(700 BYTE) NOT NULL ENABLE,
"TRIAL" VARCHAR2(50 BYTE),
 CONSTRAINT "TM_TRIAL_NODES_PK" PRIMARY KEY ("TRIAL")
 USING I2B2_INDEX
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
