--
-- Type: TABLE; Owner: I2B2METADATA; Name: TOTALNUM
--
 CREATE TABLE "I2B2METADATA"."TOTALNUM"
  (	"C_FULLNAME" VARCHAR2(850 BYTE),
"AGG_DATE" DATE,
"AGG_COUNT" NUMBER(22,0),
"TYPEFLAG_CD" VARCHAR2(3 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;

--
-- Type: INDEX; Owner: I2B2METADATA; Name: TOTALNUM_IDX
--
CREATE INDEX "I2B2METADATA"."TOTALNUM_IDX" ON "I2B2METADATA"."TOTALNUM" ("C_FULLNAME", "AGG_DATE", "TYPEFLAG_CD")
TABLESPACE "I2B2_INDEX" ;
