--
-- Type: TABLE; Owner: I2B2METADATA; Name: TOTALNUM_REPORT
--
 CREATE TABLE "I2B2METADATA"."TOTALNUM_REPORT"
  (	"C_FULLNAME" VARCHAR2(850 BYTE),
"AGG_DATE" VARCHAR2(50 BYTE),
"AGG_COUNT" NUMBER(22,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;

--
-- Type: INDEX; Owner: I2B2METADATA; Name: TOTALNUM_REPORT_IDX
--
CREATE INDEX "I2B2METADATA"."TOTALNUM_REPORT_IDX" ON "I2B2METADATA"."TOTALNUM_REPORT" ("C_FULLNAME")
TABLESPACE "I2B2_INDEX" ;
