--
-- Type: TABLE; Owner: TS_BATCH; Name: BATCH_JOB_INSTANCE
--
 CREATE TABLE "TS_BATCH"."BATCH_JOB_INSTANCE" 
  (	"JOB_INSTANCE_ID" NUMBER(18,0) NOT NULL ENABLE,
"VERSION" NUMBER(18,0),
"JOB_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE,
"JOB_KEY" VARCHAR2(32 BYTE) NOT NULL ENABLE,
CONSTRAINT "BATCH_JOB_INSTANCE_PK" PRIMARY KEY ("JOB_INSTANCE_ID")
USING INDEX
TABLESPACE "INDX" ENABLE,
CONSTRAINT "JOB_INST_UN" UNIQUE ("JOB_NAME","JOB_KEY")
USING INDEX
TABLESPACE "INDX" ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
