--
-- Type: TABLE; Owner: TS_BATCH; Name: BATCH_JOB_EXECUTION_CONTEXT
--
 CREATE TABLE "TS_BATCH"."BATCH_JOB_EXECUTION_CONTEXT" 
  (	"JOB_EXECUTION_ID" NUMBER(18,0) NOT NULL ENABLE,
"SHORT_CONTEXT" VARCHAR2(2500 BYTE) NOT NULL ENABLE, 
"SERIALIZED_CONTEXT" CLOB,
CONSTRAINT "BATCH_JOB_EXECUTION_CTXT_PK" PRIMARY KEY ("JOB_EXECUTION_ID")
USING INDEX
TABLESPACE "INDX" ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: REF_CONSTRAINT; Owner: TS_BATCH; Name: JOB_EXEC_CTX_FK
--
ALTER TABLE "TS_BATCH"."BATCH_JOB_EXECUTION_CONTEXT" ADD CONSTRAINT "JOB_EXEC_CTX_FK" FOREIGN KEY ("JOB_EXECUTION_ID")
 REFERENCES "TS_BATCH"."BATCH_JOB_EXECUTION" ("JOB_EXECUTION_ID") ENABLE;
