echo "----------------------------------------------------------------------------------"
echo "|  This script will install transmart app and data on RedHat Enterprise Linux 7.2 |"
echo "-----------------------------------------------------------------------------------"
echo "|  Note: this script uses the 'sudo' command which will time out after            |"
echo "|  15 minutes; because of this, when actions take longer then 15 minutes,         |"
echo "|  you will have to reenter the sudo password. If you wish, you can change this   |"
echo "|  behavior before running the script. To do so, kill the script now              |"
echo "|  with ^C (control-c) and follow the instructions here:                          |"
echo "|  http://rhel instructions needed/                                               |"
echo "|  Then, restart the script and enter the sudo password normally                  |"
echo "-----------------------------------------------------------------------------------"
