--
-- Type: TABLE; Owner: BIOMART_USER; Name: APPLICATION_SETTINGS
--
 CREATE TABLE "BIOMART_USER"."APPLICATION_SETTINGS"
  (	"ID" NUMBER(19,0) NOT NULL ENABLE,
"VERSION" NUMBER(19,0) NOT NULL ENABLE,
"FIELDNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
"FIELDVALUE" VARCHAR2(2000 CHAR) NOT NULL ENABLE,
"LAST_UPDATED" TIMESTAMP (6) NOT NULL ENABLE,
"USERID" NUMBER(19,0) NOT NULL ENABLE,
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS NOLOGGING
 TABLESPACE "TRANSMART" ;
