CREATE SCHEMA IF NOT EXISTS AMAPP;
CREATE SCHEMA IF NOT EXISTS BIOMART;
CREATE SCHEMA IF NOT EXISTS DEAPP;
CREATE SCHEMA IF NOT EXISTS FMAPP;
CREATE SCHEMA IF NOT EXISTS I2B2DEMODATA;
CREATE SCHEMA IF NOT EXISTS I2B2METADATA;
CREATE SCHEMA IF NOT EXISTS SEARCHAPP;
CREATE SCHEMA IF NOT EXISTS TM_LZ;
SET SCHEMA_SEARCH_PATH PUBLIC,AMAPP,BIOMART,DEAPP,FMAPP,I2B2DEMODATA,I2B2METADATA,SEARCHAPP,TM_LZ;
