--
-- Name: async_job_seq; Type: SEQUENCE; Schema: i2b2demodata; Owner: -
--
CREATE SEQUENCE async_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: protocol_id_seq; Type: SEQUENCE; Schema: i2b2demodata; Owner: -
--
CREATE SEQUENCE protocol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: seq_subject_reference; Type: SEQUENCE; Schema: i2b2demodata; Owner: -
--
CREATE SEQUENCE seq_subject_reference
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: sq_up_encdim_encounternum; Type: SEQUENCE; Schema: i2b2demodata; Owner: -
--
CREATE SEQUENCE sq_up_encdim_encounternum
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;




-- DX
CREATE TEMPORARY TABLE DX  (
	ENCOUNTER_NUM	INT,
	PATIENT_NUM		INT,
	INSTANCE_NUM	INT,
	CONCEPT_CD 		varchar(50), 
	START_DATE 		TIMESTAMP,
	PROVIDER_ID 	varchar(50), 
	temporal_start_date TIMESTAMP, 
	temporal_end_date TIMESTAMP	
	
 ) on COMMIT PRESERVE ROWS
;

create TEMPORARY TABLE TEMP_PDO_INPUTLIST    ( 
char_param1 varchar(100)
 ) ON COMMIT PRESERVE ROWS
;


-- QUERY_GLOBAL_TEMP
CREATE TEMPORARY TABLE QUERY_GLOBAL_TEMP   ( 
	ENCOUNTER_NUM	INT,
	PATIENT_NUM		INT,
	INSTANCE_NUM	INT ,
	CONCEPT_CD      VARCHAR(50),
	START_DATE	    DATE,
	PROVIDER_ID     VARCHAR(50),
	PANEL_COUNT		INT,
	FACT_COUNT		INT,
	FACT_PANELS		INT
 ) on COMMIT PRESERVE ROWS
;

-- GLOBAL_TEMP_PARAM_TABLE
 CREATE TEMPORARY TABLE GLOBAL_TEMP_PARAM_TABLE   (
	SET_INDEX	INT,
	CHAR_PARAM1	VARCHAR(500),
	CHAR_PARAM2	VARCHAR(500),
	NUM_PARAM1	INT,
	NUM_PARAM2	INT
) ON COMMIT PRESERVE ROWS
;

-- GLOBAL_TEMP_FACT_PARAM_TABLE
CREATE TEMPORARY TABLE GLOBAL_TEMP_FACT_PARAM_TABLE   (
	SET_INDEX	INT,
	CHAR_PARAM1	VARCHAR(500),
	CHAR_PARAM2	VARCHAR(500),
	NUM_PARAM1	INT,
	NUM_PARAM2	INT
) ON COMMIT PRESERVE ROWS
;

-- MASTER_QUERY_GLOBAL_TEMP
CREATE TEMPORARY TABLE MASTER_QUERY_GLOBAL_TEMP    ( 
	ENCOUNTER_NUM	INT,
	PATIENT_NUM		INT,
	INSTANCE_NUM	INT ,
	CONCEPT_CD      VARCHAR(50),
	START_DATE	    DATE,
	PROVIDER_ID     VARCHAR(50),
	MASTER_ID		VARCHAR(50),
	LEVEL_NO		INT,
	TEMPORAL_START_DATE DATE,
	TEMPORAL_END_DATE DATE
 ) ON COMMIT PRESERVE ROWS
;
