echo "---------------------------------------------------------------------"
echo "|  This script will install transmart app and data on Ubuntu 14.04  |"
echo "|  Note: this script uses the 'sudo' command which will time out    |"
echo "|  after 15 minutes; because of this, when actions that take a      |"
echo "|  longer time then 15 minutes are run, then you will have to       |"
echo "|  reenter the sudo password. If you wish, you can change this      |"
echo "|  behavior before running the script. To do so, kill the script    |"
echo "|  now with ^C (control-c) and follow the instructions here:        |"
echo "|  https://help.ubuntu.com/community/RootSudoTimeout                |"
echo "|  Then, restart the script and enter the sudo root password        |"
echo "|  normally to continue running the script.                         |"
echo "---------------------------------------------------------------------"
