//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.01 at 12:36:24 PM GMT 
//


package uk.ac.ebi.mydas.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="global">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="baseurl">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="gzipped">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="slash-das-points-to-dsn">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="default-stylesheet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="dsn-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="dna-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="entry-points-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="sequence-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="features-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="types-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *                   &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datasources">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="datasource" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="maintainer">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="version" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="coordinates" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                                               &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="taxid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="test_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="capability" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="query_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                                     &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="stylesheet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dna-command-enabled">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="features-strictly-enclosed">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="use-feature-id-for-feature-label">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="include-types-with-zero-count">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="doc_href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "global",
    "datasources"
})
@XmlRootElement(name = "mydasserver")
public class Mydasserver {

    @XmlElement(required = true)
    protected Mydasserver.Global global;
    @XmlElement(required = true)
    protected Mydasserver.Datasources datasources;

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link Mydasserver.Global }
     *     
     */
    public Mydasserver.Global getGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mydasserver.Global }
     *     
     */
    public void setGlobal(Mydasserver.Global value) {
        this.global = value;
    }

    /**
     * Gets the value of the datasources property.
     * 
     * @return
     *     possible object is
     *     {@link Mydasserver.Datasources }
     *     
     */
    public Mydasserver.Datasources getDatasources() {
        return datasources;
    }

    /**
     * Sets the value of the datasources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mydasserver.Datasources }
     *     
     */
    public void setDatasources(Mydasserver.Datasources value) {
        this.datasources = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="datasource" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="maintainer">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="version" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="coordinates" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                                     &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="taxid" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="test_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="capability" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="query_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                           &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="stylesheet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="dna-command-enabled">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="features-strictly-enclosed">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="use-feature-id-for-feature-label">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="include-types-with-zero-count">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="doc_href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datasource"
    })
    public static class Datasources {

        @XmlElement(required = true)
        protected List<Mydasserver.Datasources.Datasource> datasource;

        /**
         * Gets the value of the datasource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the datasource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDatasource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mydasserver.Datasources.Datasource }
         * 
         * 
         */
        public List<Mydasserver.Datasources.Datasource> getDatasource() {
            if (datasource == null) {
                datasource = new ArrayList<Mydasserver.Datasources.Datasource>();
            }
            return this.datasource;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="maintainer">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="version" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="coordinates" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *                           &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="taxid" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="test_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="capability" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="query_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *                 &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="stylesheet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="dna-command-enabled">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="features-strictly-enclosed">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="use-feature-id-for-feature-label">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="include-types-with-zero-count">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="doc_href" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "maintainer",
            "version",
            "stylesheet",
            "dnaCommandEnabled",
            "featuresStrictlyEnclosed",
            "useFeatureIdForFeatureLabel",
            "includeTypesWithZeroCount",
            "property"
        })
        public static class Datasource {

            @XmlElement(required = true)
            protected Mydasserver.Datasources.Datasource.Maintainer maintainer;
            @XmlElement(required = true)
            protected List<Mydasserver.Datasources.Datasource.Version> version;
            protected String stylesheet;
            @XmlElement(name = "dna-command-enabled", required = true)
            protected Mydasserver.Datasources.Datasource.DnaCommandEnabled dnaCommandEnabled;
            @XmlElement(name = "features-strictly-enclosed", required = true)
            protected Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed featuresStrictlyEnclosed;
            @XmlElement(name = "use-feature-id-for-feature-label", required = true)
            protected Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel useFeatureIdForFeatureLabel;
            @XmlElement(name = "include-types-with-zero-count", required = true)
            protected Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount includeTypesWithZeroCount;
            protected List<PropertyType> property;
            @XmlAttribute(name = "uri", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String uri;
            @XmlAttribute(name = "title", required = true)
            protected String title;
            @XmlAttribute(name = "description", required = true)
            protected String description;
            @XmlAttribute(name = "doc_href")
            @XmlSchemaType(name = "anyURI")
            protected String docHref;

            /**
             * Gets the value of the maintainer property.
             * 
             * @return
             *     possible object is
             *     {@link Mydasserver.Datasources.Datasource.Maintainer }
             *     
             */
            public Mydasserver.Datasources.Datasource.Maintainer getMaintainer() {
                return maintainer;
            }

            /**
             * Sets the value of the maintainer property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mydasserver.Datasources.Datasource.Maintainer }
             *     
             */
            public void setMaintainer(Mydasserver.Datasources.Datasource.Maintainer value) {
                this.maintainer = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the version property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVersion().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Mydasserver.Datasources.Datasource.Version }
             * 
             * 
             */
            public List<Mydasserver.Datasources.Datasource.Version> getVersion() {
                if (version == null) {
                    version = new ArrayList<Mydasserver.Datasources.Datasource.Version>();
                }
                return this.version;
            }

            /**
             * Gets the value of the stylesheet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStylesheet() {
                return stylesheet;
            }

            /**
             * Sets the value of the stylesheet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStylesheet(String value) {
                this.stylesheet = value;
            }

            /**
             * Gets the value of the dnaCommandEnabled property.
             * 
             * @return
             *     possible object is
             *     {@link Mydasserver.Datasources.Datasource.DnaCommandEnabled }
             *     
             */
            public Mydasserver.Datasources.Datasource.DnaCommandEnabled getDnaCommandEnabled() {
                return dnaCommandEnabled;
            }

            /**
             * Sets the value of the dnaCommandEnabled property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mydasserver.Datasources.Datasource.DnaCommandEnabled }
             *     
             */
            public void setDnaCommandEnabled(Mydasserver.Datasources.Datasource.DnaCommandEnabled value) {
                this.dnaCommandEnabled = value;
            }

            /**
             * Gets the value of the featuresStrictlyEnclosed property.
             * 
             * @return
             *     possible object is
             *     {@link Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed }
             *     
             */
            public Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed getFeaturesStrictlyEnclosed() {
                return featuresStrictlyEnclosed;
            }

            /**
             * Sets the value of the featuresStrictlyEnclosed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed }
             *     
             */
            public void setFeaturesStrictlyEnclosed(Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed value) {
                this.featuresStrictlyEnclosed = value;
            }

            /**
             * Gets the value of the useFeatureIdForFeatureLabel property.
             * 
             * @return
             *     possible object is
             *     {@link Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel }
             *     
             */
            public Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel getUseFeatureIdForFeatureLabel() {
                return useFeatureIdForFeatureLabel;
            }

            /**
             * Sets the value of the useFeatureIdForFeatureLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel }
             *     
             */
            public void setUseFeatureIdForFeatureLabel(Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel value) {
                this.useFeatureIdForFeatureLabel = value;
            }

            /**
             * Gets the value of the includeTypesWithZeroCount property.
             * 
             * @return
             *     possible object is
             *     {@link Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount }
             *     
             */
            public Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount getIncludeTypesWithZeroCount() {
                return includeTypesWithZeroCount;
            }

            /**
             * Sets the value of the includeTypesWithZeroCount property.
             * 
             * @param value
             *     allowed object is
             *     {@link Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount }
             *     
             */
            public void setIncludeTypesWithZeroCount(Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount value) {
                this.includeTypesWithZeroCount = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the property property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PropertyType }
             * 
             * 
             */
            public List<PropertyType> getProperty() {
                if (property == null) {
                    property = new ArrayList<PropertyType>();
                }
                return this.property;
            }

            /**
             * Gets the value of the uri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUri() {
                return uri;
            }

            /**
             * Sets the value of the uri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUri(String value) {
                this.uri = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the docHref property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDocHref() {
                return docHref;
            }

            /**
             * Sets the value of the docHref property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDocHref(String value) {
                this.docHref = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DnaCommandEnabled {

                @XmlValue
                protected boolean value;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public boolean isValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(boolean value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class FeaturesStrictlyEnclosed {

                @XmlValue
                protected boolean value;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public boolean isValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(boolean value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class IncludeTypesWithZeroCount {

                @XmlValue
                protected boolean value;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public boolean isValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(boolean value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Maintainer {

                @XmlAttribute(name = "email", required = true)
                protected String email;

                /**
                 * Gets the value of the email property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getEmail() {
                    return email;
                }

                /**
                 * Sets the value of the email property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setEmail(String value) {
                    this.email = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class UseFeatureIdForFeatureLabel {

                @XmlValue
                protected boolean value;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public boolean isValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(boolean value) {
                    this.value = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="coordinates" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
             *                 &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="taxid" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="test_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="capability" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="query_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
             *       &lt;attribute name="created" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "clazz",
                "coordinates",
                "capability",
                "property"
            })
            public static class Version {

                @XmlElement(name = "class", required = true)
                protected String clazz;
                @XmlElement(required = true)
                protected List<Mydasserver.Datasources.Datasource.Version.Coordinates> coordinates;
                @XmlElement(required = true)
                protected List<Mydasserver.Datasources.Datasource.Version.Capability> capability;
                protected List<PropertyType> property;
                @XmlAttribute(name = "uri", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String uri;
                @XmlAttribute(name = "created", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar created;
 
                /**
                 * Gets the value of the clazz property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClazz() {
                    return clazz;
                }

                /**
                 * Sets the value of the clazz property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClazz(String value) {
                    this.clazz = value;
                }

                /**
                 * Gets the value of the coordinates property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the coordinates property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCoordinates().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Mydasserver.Datasources.Datasource.Version.Coordinates }
                 * 
                 * 
                 */
                public List<Mydasserver.Datasources.Datasource.Version.Coordinates> getCoordinates() {
                    if (coordinates == null) {
                        coordinates = new ArrayList<Mydasserver.Datasources.Datasource.Version.Coordinates>();
                    }
                    return this.coordinates;
                }

                /**
                 * Gets the value of the capability property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the capability property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCapability().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Mydasserver.Datasources.Datasource.Version.Capability }
                 * 
                 * 
                 */
                public List<Mydasserver.Datasources.Datasource.Version.Capability> getCapability() {
                    if (capability == null) {
                        capability = new ArrayList<Mydasserver.Datasources.Datasource.Version.Capability>();
                    }
                    return this.capability;
                }

                /**
                 * Gets the value of the property property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the property property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getProperty().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PropertyType }
                 * 
                 * 
                 */
                public List<PropertyType> getProperty() {
                    if (property == null) {
                        property = new ArrayList<PropertyType>();
                    }
                    return this.property;
                }

                /**
                 * Gets the value of the uri property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUri() {
                    return uri;
                }

                /**
                 * Sets the value of the uri property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUri(String value) {
                    this.uri = value;
                }

                /**
                 * Gets the value of the created property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getCreated() {
                    return created;
                }

                /**
                 * Sets the value of the created property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setCreated(XMLGregorianCalendar value) {
                    this.created = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="query_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Capability {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "type", required = true)
                    protected String type;
                    @XmlAttribute(name = "query_uri")
                    @XmlSchemaType(name = "anyURI")
                    protected String queryUri;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the queryUri property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getQueryUri() {
                        return queryUri;
                    }

                    /**
                     * Sets the value of the queryUri property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setQueryUri(String value) {
                        this.queryUri = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="uri" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
                 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="authority" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="taxid" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="test_range" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Coordinates {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "uri", required = true)
                    @XmlSchemaType(name = "anyURI")
                    protected String uri;
                    @XmlAttribute(name = "source", required = true)
                    protected String source;
                    @XmlAttribute(name = "authority", required = true)
                    protected String authority;
                    @XmlAttribute(name = "taxid")
                    protected String taxid;
                    @XmlAttribute(name = "version")
                    protected String version;
                    @XmlAttribute(name = "test_range", required = true)
                    protected String testRange;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the uri property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUri() {
                        return uri;
                    }

                    /**
                     * Sets the value of the uri property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUri(String value) {
                        this.uri = value;
                    }

                    /**
                     * Gets the value of the source property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSource() {
                        return source;
                    }

                    /**
                     * Sets the value of the source property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSource(String value) {
                        this.source = value;
                    }

                    /**
                     * Gets the value of the authority property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAuthority() {
                        return authority;
                    }

                    /**
                     * Sets the value of the authority property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAuthority(String value) {
                        this.authority = value;
                    }

                    /**
                     * Gets the value of the taxid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTaxid() {
                        return taxid;
                    }

                    /**
                     * Sets the value of the taxid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTaxid(String value) {
                        this.taxid = value;
                    }

                    /**
                     * Gets the value of the version property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getVersion() {
                        return version;
                    }

                    /**
                     * Sets the value of the version property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setVersion(String value) {
                        this.version = value;
                    }

                    /**
                     * Gets the value of the testRange property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTestRange() {
                        return testRange;
                    }

                    /**
                     * Sets the value of the testRange property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTestRange(String value) {
                        this.testRange = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="baseurl">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="gzipped">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="slash-das-points-to-dsn">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="default-stylesheet" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="dsn-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="dna-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="entry-points-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="sequence-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="features-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="types-xslt-url" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
     *         &lt;element name="property" type="{}propertyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "baseurl",
        "gzipped",
        "slashDasPointsToDsn",
        "defaultStylesheet",
        "dsnXsltUrl",
        "dnaXsltUrl",
        "entryPointsXsltUrl",
        "sequenceXsltUrl",
        "featuresXsltUrl",
        "typesXsltUrl",
        "property"
    })
    public static class Global {

        @XmlElement(required = true)
        protected Mydasserver.Global.Baseurl baseurl;
        @XmlElement(required = true)
        protected Mydasserver.Global.Gzipped gzipped;
        @XmlElement(name = "slash-das-points-to-dsn", required = true)
        protected Mydasserver.Global.SlashDasPointsToDsn slashDasPointsToDsn;
        @XmlElement(name = "default-stylesheet", required = true)
        protected String defaultStylesheet;
        @XmlElement(name = "dsn-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String dsnXsltUrl;
        @XmlElement(name = "dna-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String dnaXsltUrl;
        @XmlElement(name = "entry-points-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String entryPointsXsltUrl;
        @XmlElement(name = "sequence-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String sequenceXsltUrl;
        @XmlElement(name = "features-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String featuresXsltUrl;
        @XmlElement(name = "types-xslt-url")
        @XmlSchemaType(name = "anyURI")
        protected String typesXsltUrl;
        protected List<PropertyType> property;

        /**
         * Gets the value of the baseurl property.
         * 
         * @return
         *     possible object is
         *     {@link Mydasserver.Global.Baseurl }
         *     
         */
        public Mydasserver.Global.Baseurl getBaseurl() {
            return baseurl;
        }

        /**
         * Sets the value of the baseurl property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mydasserver.Global.Baseurl }
         *     
         */
        public void setBaseurl(Mydasserver.Global.Baseurl value) {
            this.baseurl = value;
        }

        /**
         * Gets the value of the gzipped property.
         * 
         * @return
         *     possible object is
         *     {@link Mydasserver.Global.Gzipped }
         *     
         */
        public Mydasserver.Global.Gzipped getGzipped() {
            return gzipped;
        }

        /**
         * Sets the value of the gzipped property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mydasserver.Global.Gzipped }
         *     
         */
        public void setGzipped(Mydasserver.Global.Gzipped value) {
            this.gzipped = value;
        }

        /**
         * Gets the value of the slashDasPointsToDsn property.
         * 
         * @return
         *     possible object is
         *     {@link Mydasserver.Global.SlashDasPointsToDsn }
         *     
         */
        public Mydasserver.Global.SlashDasPointsToDsn getSlashDasPointsToDsn() {
            return slashDasPointsToDsn;
        }

        /**
         * Sets the value of the slashDasPointsToDsn property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mydasserver.Global.SlashDasPointsToDsn }
         *     
         */
        public void setSlashDasPointsToDsn(Mydasserver.Global.SlashDasPointsToDsn value) {
            this.slashDasPointsToDsn = value;
        }

        /**
         * Gets the value of the defaultStylesheet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultStylesheet() {
            return defaultStylesheet;
        }

        /**
         * Sets the value of the defaultStylesheet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultStylesheet(String value) {
            this.defaultStylesheet = value;
        }

        /**
         * Gets the value of the dsnXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDsnXsltUrl() {
            return dsnXsltUrl;
        }

        /**
         * Sets the value of the dsnXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDsnXsltUrl(String value) {
            this.dsnXsltUrl = value;
        }

        /**
         * Gets the value of the dnaXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDnaXsltUrl() {
            return dnaXsltUrl;
        }

        /**
         * Sets the value of the dnaXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDnaXsltUrl(String value) {
            this.dnaXsltUrl = value;
        }

        /**
         * Gets the value of the entryPointsXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntryPointsXsltUrl() {
            return entryPointsXsltUrl;
        }

        /**
         * Sets the value of the entryPointsXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntryPointsXsltUrl(String value) {
            this.entryPointsXsltUrl = value;
        }

        /**
         * Gets the value of the sequenceXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSequenceXsltUrl() {
            return sequenceXsltUrl;
        }

        /**
         * Sets the value of the sequenceXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSequenceXsltUrl(String value) {
            this.sequenceXsltUrl = value;
        }

        /**
         * Gets the value of the featuresXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFeaturesXsltUrl() {
            return featuresXsltUrl;
        }

        /**
         * Sets the value of the featuresXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFeaturesXsltUrl(String value) {
            this.featuresXsltUrl = value;
        }

        /**
         * Gets the value of the typesXsltUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTypesXsltUrl() {
            return typesXsltUrl;
        }

        /**
         * Sets the value of the typesXsltUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTypesXsltUrl(String value) {
            this.typesXsltUrl = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PropertyType }
         * 
         * 
         */
        public List<PropertyType> getProperty() {
            if (property == null) {
                property = new ArrayList<PropertyType>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Baseurl {

            @XmlValue
            @XmlSchemaType(name = "anyURI")
            protected String value;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Gzipped {

            @XmlValue
            protected boolean value;

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>boolean">
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class SlashDasPointsToDsn {

            @XmlValue
            protected boolean value;

            /**
             * Gets the value of the value property.
             * 
             */
            public boolean isValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(boolean value) {
                this.value = value;
            }

        }

    }

}
