//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.23 at 02:21:44 PM GMT 
//


package uk.ac.ebi.mydas.configuration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mydasserver.Global.SlashDasPointsToDsn }
     * 
     */
    public Mydasserver.Global.SlashDasPointsToDsn createMydasserverGlobalSlashDasPointsToDsn() {
        return new Mydasserver.Global.SlashDasPointsToDsn();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount }
     * 
     */
    public Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount createMydasserverDatasourcesDatasourceIncludeTypesWithZeroCount() {
        return new Mydasserver.Datasources.Datasource.IncludeTypesWithZeroCount();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources.Datasource }
     * 
     */
    public Mydasserver.Datasources.Datasource createMydasserverDatasourcesDatasource() {
        return new Mydasserver.Datasources.Datasource();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed }
     * 
     */
    public Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed createMydasserverDatasourcesDatasourceFeaturesStrictlyEnclosed() {
        return new Mydasserver.Datasources.Datasource.FeaturesStrictlyEnclosed();
    }

    /**
     * Create an instance of {@link Mydasserver.Global.Gzipped }
     * 
     */
    public Mydasserver.Global.Gzipped createMydasserverGlobalGzipped() {
        return new Mydasserver.Global.Gzipped();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources.Datasource.DnaCommandEnabled }
     * 
     */
    public Mydasserver.Datasources.Datasource.DnaCommandEnabled createMydasserverDatasourcesDatasourceDnaCommandEnabled() {
        return new Mydasserver.Datasources.Datasource.DnaCommandEnabled();
    }

    /**
     * Create an instance of {@link Mydasserver.Global.Baseurl }
     * 
     */
    public Mydasserver.Global.Baseurl createMydasserverGlobalBaseurl() {
        return new Mydasserver.Global.Baseurl();
    }

    /**
     * Create an instance of {@link Mydasserver.Global }
     * 
     */
    public Mydasserver.Global createMydasserverGlobal() {
        return new Mydasserver.Global();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel }
     * 
     */
    public Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel createMydasserverDatasourcesDatasourceUseFeatureIdForFeatureLabel() {
        return new Mydasserver.Datasources.Datasource.UseFeatureIdForFeatureLabel();
    }

    /**
     * Create an instance of {@link Mydasserver }
     * 
     */
    public Mydasserver createMydasserver() {
        return new Mydasserver();
    }

    /**
     * Create an instance of {@link Mydasserver.Datasources }
     * 
     */
    public Mydasserver.Datasources createMydasserverDatasources() {
        return new Mydasserver.Datasources();
    }

}
