--
-- Type: TABLE; Owner: AMAPP; Name: AM_TAG_ASSOCIATION
--
 CREATE TABLE "AMAPP"."AM_TAG_ASSOCIATION" 
  (	"SUBJECT_UID" VARCHAR2(300) NOT NULL ENABLE, 
"OBJECT_UID" VARCHAR2(300) NOT NULL ENABLE, 
"OBJECT_TYPE" VARCHAR2(50), 
"TAG_ITEM_ID" NUMBER(18,0), 
 CONSTRAINT "AM_TAG_ASSOCIATION_PK" PRIMARY KEY ("SUBJECT_UID", "OBJECT_UID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

