--
-- Type: TABLE; Owner: I2B2PM; Name: PM_APPROVALS_PARAMS
--
 CREATE TABLE "I2B2PM"."PM_APPROVALS_PARAMS"
  (	"ID" NUMBER NOT NULL ENABLE,
"APPROVAL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"PARAM_NAME_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"VALUE" CLOB,
"ACTIVATION_DATE" DATE,
"EXPIRATION_DATE" DATE,
"DATATYPE_CD" VARCHAR2(50 BYTE),
"OBJECT_CD" VARCHAR2(50 BYTE),
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_APPROVALS_PARAMS_PK" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2"
LOB ("VALUE") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
