--
-- Type: TABLE; Owner: I2B2PM; Name: PM_APPROVALS
--
 CREATE TABLE "I2B2PM"."PM_APPROVALS"
  (	"APPROVAL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"APPROVAL_NAME" VARCHAR2(255 BYTE),
"APPROVAL_DESCRIPTION" VARCHAR2(2000 BYTE),
"APPROVAL_ACTIVATION_DATE" DATE,
"APPROVAL_EXPIRATION_DATE" DATE,
"OBJECT_CD" VARCHAR2(50 BYTE),
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2" ;
