--
-- Type: TABLE; Owner: I2B2PM; Name: PM_CELL_DATA
--
 CREATE TABLE "I2B2PM"."PM_CELL_DATA"
  (	"CELL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"PROJECT_PATH" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"NAME" VARCHAR2(255 BYTE),
"METHOD_CD" VARCHAR2(255 BYTE),
"URL" VARCHAR2(255 BYTE),
"CAN_OVERRIDE" NUMBER(1,0),
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_CELL_DATA_PK" PRIMARY KEY ("CELL_ID", "PROJECT_PATH")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
