--
-- Type: TABLE; Owner: I2B2PM; Name: PM_HIVE_DATA
--
 CREATE TABLE "I2B2PM"."PM_HIVE_DATA"
  (	"DOMAIN_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"HELPURL" VARCHAR2(255 BYTE),
"DOMAIN_NAME" VARCHAR2(255 BYTE),
"ENVIRONMENT_CD" VARCHAR2(255 BYTE),
"ACTIVE" NUMBER(1,0),
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_HIVE_DATA_PK" PRIMARY KEY ("DOMAIN_ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
