--
-- Type: TABLE; Owner: I2B2PM; Name: PM_PROJECT_USER_ROLES
--
 CREATE TABLE "I2B2PM"."PM_PROJECT_USER_ROLES"
  (	"PROJECT_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"USER_ROLE_CD" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_PROJECT_USER_ROLES_PK" PRIMARY KEY ("PROJECT_ID", "USER_ID", "USER_ROLE_CD")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
