--
-- Type: TABLE; Owner: I2B2PM; Name: PM_ROLE_REQUIREMENT
--
 CREATE TABLE "I2B2PM"."PM_ROLE_REQUIREMENT"
  (	"TABLE_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"COLUMN_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"READ_HIVEMGMT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"WRITE_HIVEMGMT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"NAME_CHAR" VARCHAR2(2000 BYTE),
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_ROLE_REQUIREMENT_PK" PRIMARY KEY ("TABLE_CD", "COLUMN_CD", "READ_HIVEMGMT_CD", "WRITE_HIVEMGMT_CD")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
