--
-- Type: TABLE; Owner: I2B2PM; Name: PM_USER_SESSION
--
 CREATE TABLE "I2B2PM"."PM_USER_SESSION"
  (	"USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"SESSION_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"EXPIRED_DATE" DATE,
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "PM_USER_SESSION_PK" PRIMARY KEY ("SESSION_ID", "USER_ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2" ;
