--
-- Type: TABLE; Owner: I2B2PM; Name: PM_USER_LOGIN
--
 CREATE TABLE "I2B2PM"."PM_USER_LOGIN"
  (	"USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"ATTEMPT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"ENTRY_DATE" TIMESTAMP (6) NOT NULL ENABLE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2" ;
--
-- Name: PM_USER_LOGIN_IDX; Type: INDEX; Schema: i2b2pm; Owner: -
--
CREATE INDEX "I2B2PM"."PM_USER_LOGIN_IDX" ON "I2B2PM"."PM_USER_LOGIN" ("USER_ID", "ENTRY_DATE")
TABLESPACE "I2B2_INDEX" ;
