--
-- Type: TABLE; Owner: I2B2HIVE; Name: CRC_ANALYSIS_JOB
--
 CREATE TABLE "I2B2HIVE"."CRC_ANALYSIS_JOB"
  (	"JOB_ID" VARCHAR2(10 BYTE),
"QUEUE_NAME" VARCHAR2(50 BYTE),
"STATUS_TYPE_ID" NUMBER(*,0),
"DOMAIN_ID" VARCHAR2(255 BYTE),
"PROJECT_ID" VARCHAR2(500 BYTE),
"USER_ID" VARCHAR2(255 BYTE),
"REQUEST_XML" CLOB,
"CREATE_DATE" DATE,
"UPDATE_DATE" DATE,
 CONSTRAINT "ANALSIS_JOB_PK" PRIMARY KEY ("JOB_ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2"
LOB ("REQUEST_XML") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--
-- Type: INDEX; Owner: I2B2HIVE; Name: CRC_IDX_AJ_QNSTID
--
CREATE INDEX "I2B2HIVE"."CRC_IDX_AJ_QNSTID" ON "I2B2HIVE"."CRC_ANALYSIS_JOB" ("QUEUE_NAME", "STATUS_TYPE_ID")
TABLESPACE "I2B2_INDEX" ;
