--
-- Type: TABLE; Owner: I2B2HIVE; Name: HIVE_CELL_PARAMS
--
 CREATE TABLE "I2B2HIVE"."HIVE_CELL_PARAMS"
  (	"ID" NUMBER NOT NULL ENABLE,
"DATATYPE_CD" VARCHAR2(50 BYTE),
"CELL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"PARAM_NAME_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE,
"VALUE" CLOB,
"CHANGE_DATE" DATE,
"ENTRY_DATE" DATE,
"CHANGEBY_CHAR" VARCHAR2(50 BYTE),
"STATUS_CD" VARCHAR2(50 BYTE),
 CONSTRAINT "HIVE_CE__PK" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2"
LOB ("VALUE") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
