COMMON_DIR := /home/transmart/transmart/transmart-data/data/common
THIS_SCHEMA := biomart_user
include ../makefile.inc
include ../../common/biomart_user/makefile.inc

read_cms_file:
		groovy -cp '$(CP_ORA)' read_cms_file.groovy

