--
-- Type: TABLE; Owner: TM_WZ; Name: I2B2_LOAD_PATH
--
 CREATE TABLE "TM_WZ"."I2B2_LOAD_PATH" 
  (	"PATH" VARCHAR2(700 BYTE), 
"RECORD_ID" ROWID, 
 CONSTRAINT "I2B2_LOAD_PATH_PK" PRIMARY KEY ("PATH", "RECORD_ID")
 USING INDEX
 TABLESPACE "INDX" ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
