--
-- Type: TABLE; Owner: TM_WZ; Name: WT_SUBJECT_MIRNA_CALCS
--
 CREATE TABLE "TM_WZ"."WT_SUBJECT_MIRNA_CALCS" 
  (	"TRIAL_NAME" VARCHAR2(100 BYTE), 
"PROBESET_ID" NUMBER(18,0),
"MEAN_INTENSITY" NUMBER, 
"MEDIAN_INTENSITY" NUMBER, 
"STDDEV_INTENSITY" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

