--
-- Type: TABLE; Owner: TM_WZ; Name: WT_SUBJECT_RNASEQ_LOGS
--
 CREATE TABLE "TM_WZ"."WT_SUBJECT_RNASEQ_LOGS"
  (    "REGION_ID" NUMBER,
       "READCOUNT" NUMBER,
       "ASSAY_ID" NUMBER(18,0),
       "PATIENT_ID" NUMBER(18,0),
       "TRIAL_NAME" VARCHAR2(100 BYTE),
       "LOG_READCOUNT" NUMBER,
       "RAW_READCOUNT" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART";
--
-- Type: INDEX; Owner: TM_WZ; Name: WT_SUBJECT_RNASEQ_LOGS_I1
--
CREATE INDEX "TM_WZ"."WT_SUBJECT_RNASEQ_LOGS_I1" ON "TM_WZ"."WT_SUBJECT_RNASEQ_LOGS" ("TRIAL_NAME", "REGION_ID")
TABLESPACE "INDX" ;
