--
-- Type: TABLE; Owner: TM_WZ; Name: WT_SUBJECT_METABOLOMICS_CALCS
--
 CREATE TABLE "TM_WZ"."WT_SUBJECT_METABOLOMICS_CALCS" 
  (	"TRIAL_NAME" VARCHAR2(100 BYTE), 
"PROBESET" VARCHAR2(500 BYTE), 
"MEAN_INTENSITY" NUMBER(38,4), 
"MEDIAN_INTENSITY" NUMBER(38,4), 
"STDDEV_INTENSITY" NUMBER(38,4)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

