DROP TABLESPACE transmart INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE indx INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE i2b2 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE i2b2_index INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
