\i biomart_user/prelude.sql
\i biomart_user/functions/i2b2_bulk_add_search_term.sql
\i biomart_user/functions/i2b2_metabolomics_zscore_calc.sql
\i biomart_user/functions/instr.sql
\i biomart_user/_misc.sql
\i biomart_user/application_settings.sql
\i biomart_user/cms_section.sql
\i biomart_user/gene_ontology.sql
\i biomart_user/gene_ontology_data.sql
