--
-- Type: USER; Name: I2B2DEMODATA
--
CREATE USER "I2B2DEMODATA" IDENTIFIED BY demouser
   DEFAULT TABLESPACE "I2B2"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: I2B2DEMODATA
--
GRANT "CONNECT" TO "I2B2DEMODATA";
GRANT "RESOURCE" TO "I2B2DEMODATA";
--
-- Type: TABLESPACE_QUOTA; Name: I2B2DEMODATA
--
  DECLARE
  TEMP_COUNT NUMBER;
  SQLSTR VARCHAR2(200);
BEGIN
  SQLSTR := 'ALTER USER "I2B2DEMODATA" QUOTA UNLIMITED ON "I2B2"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES
              WHERE TABLESPACE_NAME = ''I2B2'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN;
      ELSE RAISE;
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "I2B2DEMODATA" QUOTA UNLIMITED ON "I2B2"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''I2B2'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "I2B2DEMODATA" QUOTA UNLIMITED ON "I2B2_INDEX"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''I2B2_INDEX'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
--
-- Type: SYSTEM_GRANT; Name: I2B2DEMODATA
--
GRANT CREATE SESSION TO "I2B2DEMODATA";
GRANT UNLIMITED TABLESPACE TO "I2B2DEMODATA";
GRANT CREATE TABLE TO "I2B2DEMODATA";
GRANT CREATE VIEW TO "I2B2DEMODATA";
GRANT CREATE SEQUENCE TO "I2B2DEMODATA";
GRANT CREATE ROLE TO "I2B2DEMODATA";
GRANT CREATE PROCEDURE TO "I2B2DEMODATA";
GRANT CREATE TRIGGER TO "I2B2DEMODATA";
GRANT CREATE TYPE TO "I2B2DEMODATA";
