--
-- Type: TABLE; Owner: BIOMART; Name: BIO_CGDCP_DATA
--
 CREATE TABLE "BIOMART"."BIO_CGDCP_DATA" 
  (	"EVIDENCE_CODE" VARCHAR2(200), 
"NEGATION_INDICATOR" CHAR(1 CHAR), 
"CELL_LINE_ID" NUMBER(18,0), 
"NCI_DISEASE_CONCEPT_CODE" VARCHAR2(200), 
"NCI_ROLE_CODE" VARCHAR2(200), 
"NCI_DRUG_CONCEPT_CODE" VARCHAR2(200), 
"BIO_DATA_ID" NUMBER(18,0) NOT NULL ENABLE, 
 CONSTRAINT "BIO_CGDCP_DATA_PK" PRIMARY KEY ("BIO_DATA_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

