--
-- Type: TABLE; Owner: BIOMART; Name: BIO_SPECIES_ORGANISM
--
 CREATE TABLE "BIOMART"."BIO_SPECIES_ORGANISM" 
  (	"ID" NUMBER, 
"SPECIES" VARCHAR2(100 BYTE), 
"ORGANISM" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

