-- used in view vw_faceted_search_disease
-- with hard-coded table names
--
-- Type: TABLE; Owner: BIOMART; Name: MESH
--
 CREATE TABLE "BIOMART"."MESH"
  (	"UI" VARCHAR2(20 BYTE) NOT NULL ENABLE,
"MH" VARCHAR2(200 BYTE),
"MN" VARCHAR2(200 BYTE),
"UI_PATH" VARCHAR2(500 BYTE),
 CONSTRAINT "MESH_PK" PRIMARY KEY ("UI")
 USING INDEX
 TABLESPACE "INDX"  ENABLE,
 CONSTRAINT "MESH_IDX_MN" UNIQUE ("MN")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
