--
-- Type: TABLE; Owner: BIOMART; Name: MIRNA_BIO_MARKER
--
 CREATE TABLE "BIOMART"."MIRNA_BIO_MARKER" 
  (	"BIO_MARKER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"BIO_MARKER_NAME" VARCHAR2(200), 
"BIO_MARKER_DESCRIPTION" VARCHAR2(1000), 
"ORGANISM" VARCHAR2(100), 
"PRIMARY_SOURCE_CODE" VARCHAR2(200), 
"PRIMARY_EXTERNAL_ID" VARCHAR2(200), 
"BIO_MARKER_TYPE" VARCHAR2(200) NOT NULL ENABLE, 
 CONSTRAINT "MIRNA_BM_ORG_PRI_EID_KEY" UNIQUE ("ORGANISM", "PRIMARY_EXTERNAL_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

