--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_SEARCH_KEYWORD
--
 CREATE TABLE "TM_LZ"."LT_SRC_SEARCH_KEYWORD" 
  (	"KEYWORD" VARCHAR2(300), 
"DISPLAY_CATEGORY" VARCHAR2(300), 
"DATA_CATEGORY" VARCHAR2(200), 
"SOURCE_CD" VARCHAR2(200), 
"UID_PREFIX" VARCHAR2(20), 
"UNIQUE_ID" VARCHAR2(300), 
"PARENT_TERM" VARCHAR2(300), 
"BIO_DATA_ID" VARCHAR2(300)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

