--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$U
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$U"
  (	"RID" ROWID,
 PRIMARY KEY ("RID")
 USING INDEX
 TABLESPACE "I2B2"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2"
 MONITORING ;
