--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$N
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$N"
  (	"NLT_DOCID" NUMBER(38,0),
"NLT_MARK" CHAR(1 BYTE) NOT NULL ENABLE,
 PRIMARY KEY ("NLT_DOCID") ENABLE
  ) SEGMENT CREATION IMMEDIATE
 ORGANIZATION INDEX NOCOMPRESS
 TABLESPACE "I2B2"
PCTTHRESHOLD 50
 MONITORING ;
