--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$K
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$K"
  (	"DOCID" NUMBER(38,0),
"TEXTKEY" ROWID,
 PRIMARY KEY ("TEXTKEY") ENABLE
  ) SEGMENT CREATION IMMEDIATE
 ORGANIZATION INDEX NOCOMPRESS
 TABLESPACE "I2B2"
PCTTHRESHOLD 50
 MONITORING ;
