--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$R
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$R"
  (	"ROW_NO" NUMBER(5,0),
"DATA" BLOB,
 CONSTRAINT "DR$OF_CTX_BLOB$RC" PRIMARY KEY ("ROW_NO")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2"
LOB ("DATA") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 CACHE  NOCOMPRESS  KEEP_DUPLICATES )
 MONITORING ;
