--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_PRIVILEGE
--
 CREATE TABLE "I2B2DEMODATA"."QT_PRIVILEGE"
  (	"PROTECTION_LABEL_CD" VARCHAR2(1500 BYTE) NOT NULL ENABLE,
"DATAPROT_CD" VARCHAR2(1000 BYTE),
"HIVEMGMT_CD" VARCHAR2(1000 BYTE),
"PLUGIN_ID" NUMBER(10,0),
 CONSTRAINT "QT_PRIVILEGE_PK" PRIMARY KEY ("PROTECTION_LABEL_CD")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
