--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: TIMERS
--
 CREATE TABLE "I2B2DEMODATA"."TIMERS"
  (	"TIMERID" VARCHAR2(80 BYTE) NOT NULL ENABLE,
"TARGETID" VARCHAR2(250 BYTE) NOT NULL ENABLE,
"INITIALDATE" TIMESTAMP (9) NOT NULL ENABLE,
"TIMERINTERVAL" NUMBER(19,0),
"INSTANCEPK" BLOB,
"INFO" BLOB,
 CONSTRAINT "TIMERS_PK" PRIMARY KEY ("TIMERID", "TARGETID")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2"
LOB ("INSTANCEPK") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("INFO") STORE AS SECUREFILE (
 TABLESPACE "I2B2" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
