CREATE SCHEMA IF NOT EXISTS BIOMART;
CREATE SCHEMA IF NOT EXISTS BIOMART_USER;
CREATE SCHEMA IF NOT EXISTS SEARCHAPP;
CREATE SCHEMA IF NOT EXISTS TM_LZ;
SET SCHEMA_SEARCH_PATH PUBLIC,BIOMART,BIOMART_USER,SEARCHAPP,TM_LZ;
