\i i2b2pm/prelude.sql
\i i2b2pm/_misc.sql
\i i2b2pm/pm_approvals_params.sql
\i i2b2pm/pm_approvals.sql
\i i2b2pm/pm_cell_data.sql
\i i2b2pm/pm_cell_params.sql
\i i2b2pm/pm_global_params.sql
\i i2b2pm/pm_hive_data.sql
\i i2b2pm/pm_hive_params.sql
\i i2b2pm/pm_project_data.sql
\i i2b2pm/pm_project_params.sql
\i i2b2pm/pm_project_request.sql
\i i2b2pm/pm_project_user_params.sql
\i i2b2pm/pm_project_user_roles.sql
\i i2b2pm/pm_role_requirement.sql
\i i2b2pm/pm_user_data.sql
\i i2b2pm/pm_user_login.sql
\i i2b2pm/pm_user_params.sql
\i i2b2pm/pm_user_session.sql
