--
-- Type: TABLE; Owner: I2B2WORKDATA; Name: WORKPLACE_ACCESS
--
 CREATE TABLE "I2B2WORKDATA"."WORKPLACE_ACCESS"
  (	"C_TABLE_CD" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_TABLE_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_PROTECTED_ACCESS" CHAR(1 BYTE),
"C_HLEVEL" NUMBER(*,0) NOT NULL ENABLE,
"C_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_USER_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_GROUP_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_SHARE_ID" VARCHAR2(255 BYTE),
"C_INDEX" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"C_PARENT_INDEX" VARCHAR2(255 BYTE),
"C_VISUALATTRIBUTES" CHAR(3 BYTE) NOT NULL ENABLE,
"C_TOOLTIP" VARCHAR2(255 BYTE),
"C_ENTRY_DATE" DATE,
"C_CHANGE_DATE" DATE,
"C_STATUS_CD" CHAR(1 BYTE),
 CONSTRAINT "WORKPLACE_ACCESS_PK" PRIMARY KEY ("C_INDEX")
 USING INDEX
 TABLESPACE "I2B2_INDEX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2" ;
